name: aac_app
description: "AAC app for children with autism"
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/symbols/
    - assets/icon/
